"""Render structured agent artifacts into human-readable markdown files."""
from __future__ import annotations

import json


def render_requirements_md(name: str, task: str, spec) -> str:
    lines = [
        f"# {name} — Software Requirements Specification",
        "",
        f"> Generated by the **DevForge Requirement Agent** from the task: “{task}”",
        "",
        "## 1. Overview",
        "",
        spec.overview,
        "",
        "## 2. Functional Requirements",
        "",
    ]
    lines += [f"- {fr}" for fr in spec.functional_requirements]
    lines += ["", "## 3. User Stories", ""]
    for us in spec.user_stories:
        lines.append(f"### {us.get('id', 'US')} — {us.get('title', 'Story')}")
        lines.append(f"*{us.get('story', '')}*")
        lines.append("")
        for crit in us.get("acceptance_criteria", []):
            lines.append(f"- [ ] {crit}")
        lines.append("")
    lines += ["## 4. Non-Functional Requirements", ""]
    lines += [f"- {n}" for n in spec.non_functional_requirements]
    lines += ["", "## 5. Out of Scope", ""]
    lines += [f"- {o}" for o in spec.out_of_scope]
    lines.append("")
    return "\n".join(lines)


def render_architecture_md(name: str, spec) -> str:
    lines = [
        f"# {name} — System Architecture",
        "",
        "> Generated by the **DevForge Architecture Agent**.",
        "",
        "## Summary",
        "",
        spec.summary,
        "",
        "## Tech Stack",
        "",
        "| Layer | Choice |",
        "|---|---|",
    ]
    for k, v in spec.tech_stack.items():
        lines.append(f"| {k} | {v} |")
    lines += ["", "## Directory Structure", "", "```", spec.directory_structure.strip(), "```", ""]
    lines += [
        "## API Design",
        "",
        "| Method | Path | Description | Request | Response |",
        "|---|---|---|---|---|",
    ]
    for ep in spec.api_endpoints:
        lines.append(
            f"| {ep.method} | `{ep.path}` | {ep.description} | `{ep.request_body}` | `{ep.response}` |"
        )
    lines += ["", "## Module Design", ""]
    for m in spec.modules:
        lines.append(f"### {m.name}")
        lines.append(f"{m.responsibility}")
        lines.append("")
        lines.append("Files: " + ", ".join(f"`{f}`" for f in m.files))
        lines.append("")
    lines += ["## Data Model", "", spec.data_model, ""]
    return "\n".join(lines)


def render_api_schema_json(spec) -> str:
    return json.dumps(
        [
            {
                "method": ep.method,
                "path": ep.path,
                "description": ep.description,
                "request": ep.request_body,
                "response": ep.response,
            }
            for ep in spec.api_endpoints
        ],
        indent=2,
    ) + "\n"
