"""Artifact service: versioning, workspace materialisation and status control.

Every AI (or human) output that matters is stored as an artifact — the database
row is the source of truth, the workspace file is the materialised projection.
"""
from __future__ import annotations

from sqlalchemy import desc, select
from sqlalchemy.orm import Session

from app.core.events import bus
from app.core.logging import get_logger
from app.models.artifact import Artifact, ArtifactVersion
from app.models.enums import ArtifactStatus, ArtifactType, Stage
from app.models.user import User
from app.services.workspace import WorkspaceService, content_hash

logger = get_logger("devforge.artifacts")


class ArtifactService:
    def __init__(self, db: Session, *, workspace: WorkspaceService | None = None) -> None:
        self.db = db
        self.workspace = workspace or WorkspaceService()

    # ------------------------------------------------------------------ create
    def save(
        self,
        *,
        project_id: str,
        artifact_type: ArtifactType | str,
        stage: Stage | str,
        title: str,
        content: str,
        summary: str = "",
        data: dict | None = None,
        path: str = "",
        agent_key: str | None = None,
        user: User | None = None,
        run_id: str | None = None,
        trace_refs: list[str] | None = None,
        status: ArtifactStatus | str = ArtifactStatus.DRAFT,
        new_version: bool = True,
        change_reason: str = "Generated by agent",
    ) -> Artifact:
        """Create or version an artifact and materialise it into the workspace."""
        artifact_type = str(artifact_type)
        stage = str(stage)
        existing = self.latest(project_id, artifact_type, stage)
        content_hash_value = content_hash(content)
        data = data or {}

        if existing is None:
            artifact = Artifact(
                project_id=project_id,
                run_id=run_id,
                type=artifact_type,
                stage=stage,
                title=title,
                summary=summary,
                content=content,
                data=data,
                path=path,
                content_hash=content_hash_value,
                version=1,
                status=str(status),
                produced_by_agent_key=agent_key,
                created_by_user_id=user.id if user else None,
                trace_refs=trace_refs or [],
            )
            self.db.add(artifact)
            self.db.commit()
            self.db.refresh(artifact)
        elif not new_version:
            existing.title = title or existing.title
            existing.summary = summary or existing.summary
            existing.content = content
            existing.data = data
            existing.path = path or existing.path
            existing.content_hash = content_hash_value
            existing.trace_refs = trace_refs or existing.trace_refs
            existing.status = str(status)
            self.db.commit()
            self.db.refresh(existing)
            artifact = existing
        else:
            # Keep previous revision immutable, bump the artifact to the new one.
            self.db.add(
                ArtifactVersion(
                    artifact_id=existing.id,
                    version=existing.version,
                    content=existing.content,
                    data=existing.data,
                    content_hash=existing.content_hash,
                    change_reason=change_reason,
                    author_type="AGENT" if agent_key else "USER",
                    author_label=agent_key or (user.email if user else "human"),
                )
            )
            existing.version += 1
            existing.title = title or existing.title
            existing.summary = summary or existing.summary
            existing.content = content
            existing.data = data
            existing.path = path or existing.path
            existing.content_hash = content_hash_value
            existing.trace_refs = trace_refs or existing.trace_refs
            existing.status = str(status)
            existing.produced_by_agent_key = agent_key or existing.produced_by_agent_key
            existing.run_id = run_id or existing.run_id
            self.db.commit()
            self.db.refresh(existing)
            artifact = existing

        if path:
            try:
                self.workspace.write_text(project_id, path, content)
            except Exception as exc:  # workspace failure must not lose the artifact
                logger.warning("Could not materialise artifact %s at %s: %s", artifact.id, path, exc)

        bus.emit(
            "artifact_updated",
            project_id,
            artifact_id=artifact.id,
            type=artifact.type,
            stage=artifact.stage,
            title=artifact.title,
            version=artifact.version,
            status=artifact.status,
            path=artifact.path,
        )
        return artifact

    # -------------------------------------------------------------------- read
    def latest(self, project_id: str, artifact_type: ArtifactType | str,
               stage: Stage | str | None = None) -> Artifact | None:
        stmt = select(Artifact).where(
            Artifact.project_id == project_id, Artifact.type == str(artifact_type)
        )
        if stage is not None:
            stmt = stmt.where(Artifact.stage == str(stage))
        return self.db.scalars(stmt.order_by(desc(Artifact.version), desc(Artifact.created_at))).first()

    def get(self, artifact_id: str) -> Artifact | None:
        return self.db.get(Artifact, artifact_id)

    def list_for_project(self, project_id: str, *, stage: str | None = None,
                         artifact_type: str | None = None, status: str | None = None,
                         limit: int = 100) -> list[Artifact]:
        stmt = select(Artifact).where(Artifact.project_id == project_id)
        if stage:
            stmt = stmt.where(Artifact.stage == stage)
        if artifact_type:
            stmt = stmt.where(Artifact.type == artifact_type)
        if status:
            stmt = stmt.where(Artifact.status == status)
        stmt = stmt.order_by(desc(Artifact.updated_at)).limit(limit)
        return list(self.db.scalars(stmt))

    def versions(self, artifact_id: str) -> list[ArtifactVersion]:
        stmt = (
            select(ArtifactVersion)
            .where(ArtifactVersion.artifact_id == artifact_id)
            .order_by(desc(ArtifactVersion.version))
        )
        return list(self.db.scalars(stmt))

    # ------------------------------------------------------------------ update
    def update_status(self, artifact: Artifact, status: ArtifactStatus | str) -> Artifact:
        artifact.status = str(status)
        self.db.commit()
        self.db.refresh(artifact)
        bus.emit(
            "artifact_status_changed",
            artifact.project_id,
            artifact_id=artifact.id,
            status=artifact.status,
            type=artifact.type,
            stage=artifact.stage,
        )
        return artifact

    def apply_human_edit(self, artifact: Artifact, content: str, *, user: User,
                         reason: str = "Edited by human reviewer") -> Artifact:
        """Record a human edit as a new immutable version."""
        self.db.add(
            ArtifactVersion(
                artifact_id=artifact.id,
                version=artifact.version,
                content=artifact.content,
                data=artifact.data,
                content_hash=artifact.content_hash,
                change_reason=reason,
                author_type="USER",
                author_label=user.full_name or user.email,
            )
        )
        artifact.version += 1
        artifact.content = content
        artifact.content_hash = content_hash(content)
        artifact.status = ArtifactStatus.DRAFT.value
        self.db.commit()
        self.db.refresh(artifact)
        if artifact.path:
            try:
                self.workspace.write_text(artifact.project_id, artifact.path, content)
            except Exception as exc:  # pragma: no cover
                logger.warning("Human edit not materialised to workspace: %s", exc)
        bus.emit(
            "artifact_updated",
            artifact.project_id,
            artifact_id=artifact.id,
            version=artifact.version,
            title=artifact.title,
            status=artifact.status,
            edited_by="human",
        )
        return artifact


def artifact_service(db: Session) -> ArtifactService:
    return ArtifactService(db)
