"""initial devforge schema

Revision ID: fae7eda9576e
Revises: 
Create Date: 2026-10-04 03:44:07.695323

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = 'fae7eda9576e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agents',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('role', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('stage', sa.String(length=32), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('icon', sa.String(length=32), nullable=False),
    sa.Column('capabilities', sa.JSON(), nullable=False),
    sa.Column('output_artifact_types', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('agents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agents_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_agents_key'), ['key'], unique=True)

    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=160), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('projects',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('slug', sa.String(length=220), nullable=False),
    sa.Column('requirement_input', sa.Text(), nullable=False),
    sa.Column('owner_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('current_stage', sa.String(length=32), nullable=False),
    sa.Column('workflow_status', sa.String(length=32), nullable=False),
    sa.Column('stage_status', sa.String(length=32), nullable=False),
    sa.Column('progress_percent', sa.Integer(), nullable=False),
    sa.Column('tech_stack', sa.String(length=400), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('settings', sa.JSON(), nullable=False),
    sa.Column('workspace_path', sa.String(length=600), nullable=False),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_projects_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_projects_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_projects_slug'), ['slug'], unique=True)
        batch_op.create_index(batch_op.f('ix_projects_workflow_status'), ['workflow_status'], unique=False)

    op.create_table('audit_logs',
    sa.Column('project_id', sa.Uuid(as_uuid=False), nullable=True),
    sa.Column('user_id', sa.Uuid(as_uuid=False), nullable=True),
    sa.Column('actor_type', sa.String(length=16), nullable=False),
    sa.Column('actor_label', sa.String(length=160), nullable=False),
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.Column('entity_type', sa.String(length=48), nullable=False),
    sa.Column('entity_id', sa.String(length=80), nullable=False),
    sa.Column('stage', sa.String(length=32), nullable=False),
    sa.Column('summary', sa.String(length=500), nullable=False),
    sa.Column('detail', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index('ix_audit_logs_action', ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_created_at'), ['created_at'], unique=False)
        batch_op.create_index('ix_audit_logs_project_time', ['project_id', 'created_at'], unique=False)

    op.create_table('knowledge_chunks',
    sa.Column('project_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('source_type', sa.String(length=32), nullable=False),
    sa.Column('source_ref', sa.String(length=200), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('token_estimate', sa.Integer(), nullable=False),
    sa.Column('embedding', sa.JSON(), nullable=True),
    sa.Column('embedding_model', sa.String(length=80), nullable=False),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('knowledge_chunks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_knowledge_chunks_created_at'), ['created_at'], unique=False)
        batch_op.create_index('ix_knowledge_chunks_project', ['project_id', 'source_type'], unique=False)
        batch_op.create_index('ix_knowledge_chunks_source', ['project_id', 'source_ref'], unique=False)

    op.create_table('project_members',
    sa.Column('project_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('user_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('project_role', sa.String(length=32), nullable=False),
    sa.Column('id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'user_id', name='uq_project_member')
    )
    with op.batch_alter_table('project_members', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_project_members_created_at'), ['created_at'], unique=False)
        batch_op.create_index('ix_project_members_project', ['project_id'], unique=False)

    op.create_table('repositories',
    sa.Column('project_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('owner', sa.String(length=200), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('default_branch', sa.String(length=120), nullable=False),
    sa.Column('working_branch', sa.String(length=120), nullable=False),
    sa.Column('local_path', sa.String(length=600), nullable=False),
    sa.Column('token_encrypted', sa.Text(), nullable=False),
    sa.Column('auth_configured', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_commit_sha', sa.String(length=64), nullable=False),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', name='uq_repository_project')
    )
    with op.batch_alter_table('repositories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_repositories_created_at'), ['created_at'], unique=False)

    op.create_table('tasks',
    sa.Column('project_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('priority', sa.String(length=16), nullable=False),
    sa.Column('stage', sa.String(length=32), nullable=False),
    sa.Column('assigned_agent_key', sa.String(length=64), nullable=True),
    sa.Column('requirement_refs', sa.JSON(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('created_by_user_id', sa.Uuid(as_uuid=False), nullable=True),
    sa.Column('id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tasks_created_at'), ['created_at'], unique=False)
        batch_op.create_index('ix_tasks_project_status', ['project_id', 'status'], unique=False)

    op.create_table('workflow_runs',
    sa.Column('project_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('run_number', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('engine', sa.String(length=32), nullable=False),
    sa.Column('thread_id', sa.String(length=80), nullable=False),
    sa.Column('current_stage', sa.String(length=32), nullable=False),
    sa.Column('current_node', sa.String(length=64), nullable=False),
    sa.Column('awaiting_approval', sa.Boolean(), nullable=False),
    sa.Column('pending_approval_id', sa.Uuid(as_uuid=False), nullable=True),
    sa.Column('stage_iterations', sa.JSON(), nullable=False),
    sa.Column('total_steps', sa.Integer(), nullable=False),
    sa.Column('max_stage_iterations', sa.Integer(), nullable=False),
    sa.Column('started_by_user_id', sa.Uuid(as_uuid=False), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=False),
    sa.Column('state_snapshot', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['started_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('workflow_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_workflow_runs_created_at'), ['created_at'], unique=False)
        batch_op.create_index('ix_workflow_runs_project_status', ['project_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_workflow_runs_thread_id'), ['thread_id'], unique=False)

    op.create_table('agent_executions',
    sa.Column('project_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('run_id', sa.Uuid(as_uuid=False), nullable=True),
    sa.Column('agent_key', sa.String(length=64), nullable=False),
    sa.Column('stage', sa.String(length=32), nullable=False),
    sa.Column('trigger', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('mode', sa.String(length=16), nullable=False),
    sa.Column('provider', sa.String(length=40), nullable=False),
    sa.Column('llm_model', sa.String(length=80), nullable=False),
    sa.Column('prompt_tokens', sa.Integer(), nullable=False),
    sa.Column('completion_tokens', sa.Integer(), nullable=False),
    sa.Column('total_tokens', sa.Integer(), nullable=False),
    sa.Column('input_summary', sa.Text(), nullable=False),
    sa.Column('output_summary', sa.Text(), nullable=False),
    sa.Column('error', sa.Text(), nullable=False),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['run_id'], ['workflow_runs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('agent_executions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agent_executions_created_at'), ['created_at'], unique=False)
        batch_op.create_index('ix_agent_executions_project_agent', ['project_id', 'agent_key'], unique=False)
        batch_op.create_index('ix_agent_executions_run', ['run_id'], unique=False)

    op.create_table('artifacts',
    sa.Column('project_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('run_id', sa.Uuid(as_uuid=False), nullable=True),
    sa.Column('type', sa.String(length=40), nullable=False),
    sa.Column('stage', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('path', sa.String(length=600), nullable=False),
    sa.Column('content_hash', sa.String(length=80), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('produced_by_agent_key', sa.String(length=64), nullable=True),
    sa.Column('created_by_user_id', sa.Uuid(as_uuid=False), nullable=True),
    sa.Column('trace_refs', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['run_id'], ['workflow_runs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('artifacts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_artifacts_created_at'), ['created_at'], unique=False)
        batch_op.create_index('ix_artifacts_project_stage', ['project_id', 'stage'], unique=False)
        batch_op.create_index('ix_artifacts_project_type', ['project_id', 'type'], unique=False)

    op.create_table('git_operations',
    sa.Column('project_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('repository_id', sa.Uuid(as_uuid=False), nullable=True),
    sa.Column('user_id', sa.Uuid(as_uuid=False), nullable=True),
    sa.Column('operation', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('branch', sa.String(length=120), nullable=False),
    sa.Column('commit_sha', sa.String(length=64), nullable=False),
    sa.Column('message', sa.String(length=400), nullable=False),
    sa.Column('confirmed_by_user', sa.Boolean(), nullable=False),
    sa.Column('detail', sa.JSON(), nullable=False),
    sa.Column('error', sa.Text(), nullable=False),
    sa.Column('id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('git_operations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_git_operations_created_at'), ['created_at'], unique=False)
        batch_op.create_index('ix_git_operations_project', ['project_id', 'created_at'], unique=False)

    op.create_table('workflow_states',
    sa.Column('run_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('project_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('step_index', sa.Integer(), nullable=False),
    sa.Column('node', sa.String(length=64), nullable=False),
    sa.Column('stage', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('summary', sa.String(length=400), nullable=False),
    sa.Column('state', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['run_id'], ['workflow_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('workflow_states', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_workflow_states_created_at'), ['created_at'], unique=False)
        batch_op.create_index('ix_workflow_states_run_step', ['run_id', 'step_index'], unique=False)

    op.create_table('agent_messages',
    sa.Column('project_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('agent_key', sa.String(length=64), nullable=True),
    sa.Column('thread_id', sa.String(length=80), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('user_id', sa.Uuid(as_uuid=False), nullable=True),
    sa.Column('execution_id', sa.Uuid(as_uuid=False), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['execution_id'], ['agent_executions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('agent_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agent_messages_created_at'), ['created_at'], unique=False)
        batch_op.create_index('ix_agent_messages_project_agent', ['project_id', 'agent_key', 'created_at'], unique=False)
        batch_op.create_index('ix_agent_messages_thread', ['thread_id', 'created_at'], unique=False)

    op.create_table('approvals',
    sa.Column('project_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('run_id', sa.Uuid(as_uuid=False), nullable=True),
    sa.Column('artifact_id', sa.Uuid(as_uuid=False), nullable=True),
    sa.Column('stage', sa.String(length=32), nullable=False),
    sa.Column('gate', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('requested_by_agent_key', sa.String(length=64), nullable=True),
    sa.Column('requested_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('decided_by_user_id', sa.Uuid(as_uuid=False), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('comments', sa.Text(), nullable=False),
    sa.Column('decision_meta', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['artifact_id'], ['artifacts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['decided_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['run_id'], ['workflow_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('approvals', schema=None) as batch_op:
        batch_op.create_index('ix_approvals_artifact', ['artifact_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_approvals_created_at'), ['created_at'], unique=False)
        batch_op.create_index('ix_approvals_project_status', ['project_id', 'status'], unique=False)

    op.create_table('artifact_versions',
    sa.Column('artifact_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('content_hash', sa.String(length=80), nullable=False),
    sa.Column('change_reason', sa.String(length=400), nullable=False),
    sa.Column('author_type', sa.String(length=16), nullable=False),
    sa.Column('author_label', sa.String(length=120), nullable=False),
    sa.Column('id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['artifact_id'], ['artifacts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('artifact_versions', schema=None) as batch_op:
        batch_op.create_index('ix_artifact_versions_artifact', ['artifact_id', 'version'], unique=False)
        batch_op.create_index(batch_op.f('ix_artifact_versions_created_at'), ['created_at'], unique=False)

    op.create_table('security_findings',
    sa.Column('project_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('run_id', sa.Uuid(as_uuid=False), nullable=True),
    sa.Column('artifact_id', sa.Uuid(as_uuid=False), nullable=True),
    sa.Column('scan_id', sa.String(length=64), nullable=False),
    sa.Column('rule_id', sa.String(length=40), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('file_path', sa.String(length=600), nullable=False),
    sa.Column('line', sa.Integer(), nullable=True),
    sa.Column('evidence', sa.Text(), nullable=False),
    sa.Column('recommendation', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('detected_by', sa.String(length=64), nullable=False),
    sa.Column('trace_refs', sa.JSON(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['artifact_id'], ['artifacts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['run_id'], ['workflow_runs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('security_findings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_security_findings_created_at'), ['created_at'], unique=False)
        batch_op.create_index('ix_security_findings_project', ['project_id', 'severity'], unique=False)
        batch_op.create_index('ix_security_findings_scan', ['scan_id'], unique=False)

    op.create_table('test_runs',
    sa.Column('project_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('run_id', sa.Uuid(as_uuid=False), nullable=True),
    sa.Column('artifact_id', sa.Uuid(as_uuid=False), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('total', sa.Integer(), nullable=False),
    sa.Column('passed', sa.Integer(), nullable=False),
    sa.Column('failed', sa.Integer(), nullable=False),
    sa.Column('skipped', sa.Integer(), nullable=False),
    sa.Column('errors', sa.Integer(), nullable=False),
    sa.Column('command', sa.String(length=400), nullable=False),
    sa.Column('provider', sa.String(length=40), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('triggered_by', sa.String(length=16), nullable=False),
    sa.Column('raw_output', sa.Text(), nullable=False),
    sa.Column('report', sa.JSON(), nullable=False),
    sa.Column('confirmed_by_user', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['artifact_id'], ['artifacts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['run_id'], ['workflow_runs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('test_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_test_runs_created_at'), ['created_at'], unique=False)
        batch_op.create_index('ix_test_runs_project', ['project_id', 'created_at'], unique=False)

    op.create_table('trace_links',
    sa.Column('project_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('source_type', sa.String(length=24), nullable=False),
    sa.Column('source_ref', sa.String(length=160), nullable=False),
    sa.Column('source_label', sa.String(length=400), nullable=False),
    sa.Column('target_type', sa.String(length=24), nullable=False),
    sa.Column('target_ref', sa.String(length=160), nullable=False),
    sa.Column('target_label', sa.String(length=400), nullable=False),
    sa.Column('relation', sa.String(length=32), nullable=False),
    sa.Column('artifact_id', sa.Uuid(as_uuid=False), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('note', sa.String(length=400), nullable=False),
    sa.Column('id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['artifact_id'], ['artifacts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'source_ref', 'target_ref', 'relation', name='uq_trace_link')
    )
    with op.batch_alter_table('trace_links', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_trace_links_created_at'), ['created_at'], unique=False)
        batch_op.create_index('ix_trace_links_source', ['project_id', 'source_ref'], unique=False)
        batch_op.create_index('ix_trace_links_target', ['project_id', 'target_ref'], unique=False)

    op.create_table('test_results',
    sa.Column('test_run_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('name', sa.String(length=400), nullable=False),
    sa.Column('file_path', sa.String(length=400), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('requirement_refs', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['test_run_id'], ['test_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('test_results', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_test_results_created_at'), ['created_at'], unique=False)
        batch_op.create_index('ix_test_results_run', ['test_run_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test_results', schema=None) as batch_op:
        batch_op.drop_index('ix_test_results_run')
        batch_op.drop_index(batch_op.f('ix_test_results_created_at'))

    op.drop_table('test_results')
    with op.batch_alter_table('trace_links', schema=None) as batch_op:
        batch_op.drop_index('ix_trace_links_target')
        batch_op.drop_index('ix_trace_links_source')
        batch_op.drop_index(batch_op.f('ix_trace_links_created_at'))

    op.drop_table('trace_links')
    with op.batch_alter_table('test_runs', schema=None) as batch_op:
        batch_op.drop_index('ix_test_runs_project')
        batch_op.drop_index(batch_op.f('ix_test_runs_created_at'))

    op.drop_table('test_runs')
    with op.batch_alter_table('security_findings', schema=None) as batch_op:
        batch_op.drop_index('ix_security_findings_scan')
        batch_op.drop_index('ix_security_findings_project')
        batch_op.drop_index(batch_op.f('ix_security_findings_created_at'))

    op.drop_table('security_findings')
    with op.batch_alter_table('artifact_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_artifact_versions_created_at'))
        batch_op.drop_index('ix_artifact_versions_artifact')

    op.drop_table('artifact_versions')
    with op.batch_alter_table('approvals', schema=None) as batch_op:
        batch_op.drop_index('ix_approvals_project_status')
        batch_op.drop_index(batch_op.f('ix_approvals_created_at'))
        batch_op.drop_index('ix_approvals_artifact')

    op.drop_table('approvals')
    with op.batch_alter_table('agent_messages', schema=None) as batch_op:
        batch_op.drop_index('ix_agent_messages_thread')
        batch_op.drop_index('ix_agent_messages_project_agent')
        batch_op.drop_index(batch_op.f('ix_agent_messages_created_at'))

    op.drop_table('agent_messages')
    with op.batch_alter_table('workflow_states', schema=None) as batch_op:
        batch_op.drop_index('ix_workflow_states_run_step')
        batch_op.drop_index(batch_op.f('ix_workflow_states_created_at'))

    op.drop_table('workflow_states')
    with op.batch_alter_table('git_operations', schema=None) as batch_op:
        batch_op.drop_index('ix_git_operations_project')
        batch_op.drop_index(batch_op.f('ix_git_operations_created_at'))

    op.drop_table('git_operations')
    with op.batch_alter_table('artifacts', schema=None) as batch_op:
        batch_op.drop_index('ix_artifacts_project_type')
        batch_op.drop_index('ix_artifacts_project_stage')
        batch_op.drop_index(batch_op.f('ix_artifacts_created_at'))

    op.drop_table('artifacts')
    with op.batch_alter_table('agent_executions', schema=None) as batch_op:
        batch_op.drop_index('ix_agent_executions_run')
        batch_op.drop_index('ix_agent_executions_project_agent')
        batch_op.drop_index(batch_op.f('ix_agent_executions_created_at'))

    op.drop_table('agent_executions')
    with op.batch_alter_table('workflow_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workflow_runs_thread_id'))
        batch_op.drop_index('ix_workflow_runs_project_status')
        batch_op.drop_index(batch_op.f('ix_workflow_runs_created_at'))

    op.drop_table('workflow_runs')
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_index('ix_tasks_project_status')
        batch_op.drop_index(batch_op.f('ix_tasks_created_at'))

    op.drop_table('tasks')
    with op.batch_alter_table('repositories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_repositories_created_at'))

    op.drop_table('repositories')
    with op.batch_alter_table('project_members', schema=None) as batch_op:
        batch_op.drop_index('ix_project_members_project')
        batch_op.drop_index(batch_op.f('ix_project_members_created_at'))

    op.drop_table('project_members')
    with op.batch_alter_table('knowledge_chunks', schema=None) as batch_op:
        batch_op.drop_index('ix_knowledge_chunks_source')
        batch_op.drop_index('ix_knowledge_chunks_project')
        batch_op.drop_index(batch_op.f('ix_knowledge_chunks_created_at'))

    op.drop_table('knowledge_chunks')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index('ix_audit_logs_project_time')
        batch_op.drop_index(batch_op.f('ix_audit_logs_created_at'))
        batch_op.drop_index('ix_audit_logs_action')

    op.drop_table('audit_logs')
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_projects_workflow_status'))
        batch_op.drop_index(batch_op.f('ix_projects_slug'))
        batch_op.drop_index(batch_op.f('ix_projects_name'))
        batch_op.drop_index(batch_op.f('ix_projects_created_at'))

    op.drop_table('projects')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))
        batch_op.drop_index(batch_op.f('ix_users_created_at'))

    op.drop_table('users')
    with op.batch_alter_table('agents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agents_key'))
        batch_op.drop_index(batch_op.f('ix_agents_created_at'))

    op.drop_table('agents')
    # ### end Alembic commands ###
